# Numpy

[NumPy](https://numpy.org/) is the fundamental package for scientific computing with Python.

### Installation:

<div class="alert alert-block alert-warning">
$ pip install numpy
</div>

or

<div class="alert alert-block alert-warning">
$ conda install numpy
</div>

In [1]:
import numpy as np

In [70]:
N = 1000000
my_arr = np.arange(N)
my_list = [i for i in range(N)]

In [71]:
%time for _ in range(10): my_arr2 = 2*my_arr

CPU times: user 21.6 ms, sys: 11 ms, total: 32.6 ms
Wall time: 31 ms


In [72]:
%time for _ in range(10): my_arr2 = [2*x for x in my_list]

CPU times: user 724 ms, sys: 189 ms, total: 913 ms
Wall time: 943 ms


In [74]:
943/31

30.419354838709676

## Basics:
___

One of the most commonly used functions of NumPy are *NumPy arrays*: The essential difference between lists and NumPy arrays is functionality and speed. lists give you basic operation, but NumPy adds FFTs, convolutions, fast searching, basic statistics, linear algebra, histograms, etc.

The most important difference for data science is the ability to do **element-wise calculations** with *NumPy* arrays.

`axis 0` always refers to row <br>
`axis 1` always refers to column

+ `np.array([1,2,3])`
+ `np.array([(1,2,3),(4,5,6)])`
+ `np.arange(start,stop,step)`

**Placeholders**:
- `np.linspace(0,2,9)`
- `np.zeros((1,2))`
- `np.ones((1,2))`
- `np.random.random((5,5))`
- `np.empty((2,2))`

In [8]:
arr_1d = np.array([1, 2, 3, 4])

In [11]:
arr_1d[0], arr_1d[2]

(1, 3)

In [12]:
arr_2d = np.array([[1, 2, 3, 4],
                   [4, 5, 6, 7]])

In [13]:
arr_2d

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [16]:
arr_1d.shape, arr_1d.ndim

((4,), 1)

In [17]:
arr_2d.shape, arr_2d.ndim

((2, 4), 2)

In [19]:
arr_2d[0][1], arr_2d[0, 1]

(2, 2)

In [21]:
a = np.array([[[1, 2, 3],
           [4, 5, 6]],
          [[-1, -2, -3],
           [-4, -5, -6]],
          [[10, 11, 12],
           [13, 14, 15]]])

In [23]:
a.ndim

3

In [27]:
a[0, :, :], a[1, :, :], a[2, :, :]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[-1, -2, -3],
        [-4, -5, -6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [28]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.full((4, 6), -7)

array([[-7, -7, -7, -7, -7, -7],
       [-7, -7, -7, -7, -7, -7],
       [-7, -7, -7, -7, -7, -7],
       [-7, -7, -7, -7, -7, -7]])

In [32]:
np.random.random((4, 4))

array([[0.94458335, 0.43943726, 0.35628981, 0.47134549],
       [0.99300566, 0.44859896, 0.23321315, 0.86299761],
       [0.44581564, 0.02543552, 0.18986724, 0.97633476],
       [0.77773267, 0.74815909, 0.21378286, 0.34824403]])

In [33]:
np.random.normal(0, 1, (4, 4))

array([[-1.20323854, -0.34851236,  1.29619516,  0.18127526],
       [-1.7565859 ,  0.0992279 ,  1.11456447,  0.12180711],
       [-1.26505452,  0.74914046, -1.01563608,  0.3595074 ],
       [ 0.88871653, -0.25397159,  0.85305924, -0.12508382]])

In [34]:
np.random.uniform(0, 1, (4, 4))

array([[0.67180187, 0.80593523, 0.99649754, 0.57312714],
       [0.67362217, 0.47907258, 0.51548894, 0.5439919 ],
       [0.99690028, 0.63561149, 0.18482203, 0.93211356],
       [0.43707805, 0.51598691, 0.27378695, 0.09266483]])

In [37]:
x = np.empty((5, 5))
for i in range(5):
    for j in range(5):
        x[i, j] = np.sin(i*np.pi/2)*np.cos(j*np.pi/2)

In [40]:
x

array([[ 0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  6.12323400e-17, -1.00000000e+00,
        -1.83697020e-16,  1.00000000e+00],
       [ 1.22464680e-16,  7.49879891e-33, -1.22464680e-16,
        -2.24963967e-32,  1.22464680e-16],
       [-1.00000000e+00, -6.12323400e-17,  1.00000000e+00,
         1.83697020e-16, -1.00000000e+00],
       [-2.44929360e-16, -1.49975978e-32,  2.44929360e-16,
         4.49927935e-32, -2.44929360e-16]])

In [39]:
x == 0

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [44]:
bool_inx = np.isclose(x, 0)

In [45]:
bool_inx

array([[ True,  True,  True,  True,  True],
       [False,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True, False,  True, False],
       [ True,  True,  True,  True,  True]])

In [47]:
x[bool_inx] # close to zero

array([ 0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  6.12323400e-17, -1.83697020e-16,  1.22464680e-16,
        7.49879891e-33, -1.22464680e-16, -2.24963967e-32,  1.22464680e-16,
       -6.12323400e-17,  1.83697020e-16, -2.44929360e-16, -1.49975978e-32,
        2.44929360e-16,  4.49927935e-32, -2.44929360e-16])

In [50]:
np.array([1, 2, 256], dtype=np.int8)

array([1, 2, 0], dtype=int8)

In [52]:
x[bool_inx] = 0

In [54]:
x**2

array([[0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [55]:
x.transpose()

array([[ 0.,  1.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -1.,  0.]])

In [57]:
x.T

array([[ 0.,  1.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -1.,  0.]])

In [58]:
np.exp(x)

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [2.71828183, 1.        , 0.36787944, 1.        , 2.71828183],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.36787944, 1.        , 2.71828183, 1.        , 0.36787944],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

In [59]:
x*x # element wise

array([[0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [60]:
x.dot(x) # matrix product

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Array:

+ `array.shape`	
+ `len(array)`
+ `array.ndim	`
+ `array.size`	
+ `array.dtype`	
+ `array.astype(type)`	


+ `np.copy(array)`	
+ `other = array.copy()`	
+ `array.sort()`
+ `array.sort(axis=0)`

In [64]:
x

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0., -1.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  1.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [62]:
x.mean(axis=0)

array([0., 0., 0., 0., 0.])

In [63]:
x.mean(axis=1)

array([ 0. ,  0.2,  0. , -0.2,  0. ])

In [68]:
x.var(axis=1), x.sum(axis=1), x.std(axis=1)

(array([0.  , 0.56, 0.  , 0.56, 0.  ]),
 array([ 0.,  1.,  0., -1.,  0.]),
 array([0.        , 0.74833148, 0.        , 0.74833148, 0.        ]))

## Linear Algebra:

# Scipy

[Scipy](https://scipy.org/) is the fundamental package for scientific computing with Python.

### Installation:

<div class="alert alert-block alert-warning">
$ pip install scipy
</div>